spring.application.name=MarchcatStorage
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/MarchCat
spring.datasource.username=Bogos
spring.datasource.password=07502530

mcstorage.cors.allowed-origin=http://localhost:8080