spring.application.name=MarchcatStorage
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/MarchCat
spring.datasource.username=Bogos
spring.datasource.password=07502530

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.repositories.enabled=false

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASSWORD}

mcstorage.cors.allowed-origin=http://localhost:8080